// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: proto/mpc/v1/common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 公共消息类型
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeType      string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"` // "coordinator" or "participant"
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                 // gRPC endpoint
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	RegisteredAt  string                 `protobuf:"bytes,5,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	LastHeartbeat string                 `protobuf:"bytes,6,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_mpc_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *NodeInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *NodeInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeInfo) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

func (x *NodeInfo) GetLastHeartbeat() string {
	if x != nil {
		return x.LastHeartbeat
	}
	return ""
}

func (x *NodeInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type HealthStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OverallHealthy bool                   `protobuf:"varint,1,opt,name=overall_healthy,json=overallHealthy,proto3" json:"overall_healthy,omitempty"`
	Summary        string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Checks         []*HealthCheck         `protobuf:"bytes,3,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_proto_mpc_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *HealthStatus) GetOverallHealthy() bool {
	if x != nil {
		return x.OverallHealthy
	}
	return false
}

func (x *HealthStatus) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *HealthStatus) GetChecks() []*HealthCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

type HealthCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "passing", "warning", "critical"
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	CheckedAt     string                 `protobuf:"bytes,4,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_proto_mpc_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HealthCheck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheck) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *HealthCheck) GetCheckedAt() string {
	if x != nil {
		return x.CheckedAt
	}
	return ""
}

var File_proto_mpc_v1_common_proto protoreflect.FileDescriptor

const file_proto_mpc_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x19proto/mpc/v1/common.proto\x12\x06mpc.v1\"\xbb\x02\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12#\n" +
	"\rregistered_at\x18\x05 \x01(\tR\fregisteredAt\x12%\n" +
	"\x0elast_heartbeat\x18\x06 \x01(\tR\rlastHeartbeat\x12:\n" +
	"\bmetadata\x18\a \x03(\v2\x1e.mpc.v1.NodeInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"~\n" +
	"\fHealthStatus\x12'\n" +
	"\x0foverall_healthy\x18\x01 \x01(\bR\x0eoverallHealthy\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12+\n" +
	"\x06checks\x18\x03 \x03(\v2\x13.mpc.v1.HealthCheckR\x06checks\"p\n" +
	"\vHealthCheck\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x04 \x01(\tR\tcheckedAtB0Z.github.com/kashguard/go-mpc-wallet/internal/pbb\x06proto3"

var (
	file_proto_mpc_v1_common_proto_rawDescOnce sync.Once
	file_proto_mpc_v1_common_proto_rawDescData []byte
)

func file_proto_mpc_v1_common_proto_rawDescGZIP() []byte {
	file_proto_mpc_v1_common_proto_rawDescOnce.Do(func() {
		file_proto_mpc_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mpc_v1_common_proto_rawDesc), len(file_proto_mpc_v1_common_proto_rawDesc)))
	})
	return file_proto_mpc_v1_common_proto_rawDescData
}

var file_proto_mpc_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_mpc_v1_common_proto_goTypes = []any{
	(*NodeInfo)(nil),     // 0: mpc.v1.NodeInfo
	(*HealthStatus)(nil), // 1: mpc.v1.HealthStatus
	(*HealthCheck)(nil),  // 2: mpc.v1.HealthCheck
	nil,                  // 3: mpc.v1.NodeInfo.MetadataEntry
}
var file_proto_mpc_v1_common_proto_depIdxs = []int32{
	3, // 0: mpc.v1.NodeInfo.metadata:type_name -> mpc.v1.NodeInfo.MetadataEntry
	2, // 1: mpc.v1.HealthStatus.checks:type_name -> mpc.v1.HealthCheck
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_mpc_v1_common_proto_init() }
func file_proto_mpc_v1_common_proto_init() {
	if File_proto_mpc_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mpc_v1_common_proto_rawDesc), len(file_proto_mpc_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mpc_v1_common_proto_goTypes,
		DependencyIndexes: file_proto_mpc_v1_common_proto_depIdxs,
		MessageInfos:      file_proto_mpc_v1_common_proto_msgTypes,
	}.Build()
	File_proto_mpc_v1_common_proto = out.File
	file_proto_mpc_v1_common_proto_goTypes = nil
	file_proto_mpc_v1_common_proto_depIdxs = nil
}
