// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: proto/mpc/v1/mpc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MPCNode_JoinSigningSession_FullMethodName   = "/mpc.v1.MPCNode/JoinSigningSession"
	MPCNode_SubmitSignatureShare_FullMethodName = "/mpc.v1.MPCNode/SubmitSignatureShare"
	MPCNode_Heartbeat_FullMethodName            = "/mpc.v1.MPCNode/Heartbeat"
)

// MPCNodeClient is the client API for MPCNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MPC核心服务定义
type MPCNodeClient interface {
	// 双向流：加入签名会话
	JoinSigningSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionMessage, SessionMessage], error)
	// 提交签名分片
	SubmitSignatureShare(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*ShareResponse, error)
	// 心跳检测
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type mPCNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewMPCNodeClient(cc grpc.ClientConnInterface) MPCNodeClient {
	return &mPCNodeClient{cc}
}

func (c *mPCNodeClient) JoinSigningSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionMessage, SessionMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MPCNode_ServiceDesc.Streams[0], MPCNode_JoinSigningSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SessionMessage, SessionMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MPCNode_JoinSigningSessionClient = grpc.BidiStreamingClient[SessionMessage, SessionMessage]

func (c *mPCNodeClient) SubmitSignatureShare(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*ShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareResponse)
	err := c.cc.Invoke(ctx, MPCNode_SubmitSignatureShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCNodeClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, MPCNode_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MPCNodeServer is the server API for MPCNode service.
// All implementations must embed UnimplementedMPCNodeServer
// for forward compatibility.
//
// MPC核心服务定义
type MPCNodeServer interface {
	// 双向流：加入签名会话
	JoinSigningSession(grpc.BidiStreamingServer[SessionMessage, SessionMessage]) error
	// 提交签名分片
	SubmitSignatureShare(context.Context, *ShareRequest) (*ShareResponse, error)
	// 心跳检测
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedMPCNodeServer()
}

// UnimplementedMPCNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMPCNodeServer struct{}

func (UnimplementedMPCNodeServer) JoinSigningSession(grpc.BidiStreamingServer[SessionMessage, SessionMessage]) error {
	return status.Error(codes.Unimplemented, "method JoinSigningSession not implemented")
}
func (UnimplementedMPCNodeServer) SubmitSignatureShare(context.Context, *ShareRequest) (*ShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitSignatureShare not implemented")
}
func (UnimplementedMPCNodeServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedMPCNodeServer) mustEmbedUnimplementedMPCNodeServer() {}
func (UnimplementedMPCNodeServer) testEmbeddedByValue()                 {}

// UnsafeMPCNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MPCNodeServer will
// result in compilation errors.
type UnsafeMPCNodeServer interface {
	mustEmbedUnimplementedMPCNodeServer()
}

func RegisterMPCNodeServer(s grpc.ServiceRegistrar, srv MPCNodeServer) {
	// If the following call panics, it indicates UnimplementedMPCNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MPCNode_ServiceDesc, srv)
}

func _MPCNode_JoinSigningSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MPCNodeServer).JoinSigningSession(&grpc.GenericServerStream[SessionMessage, SessionMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MPCNode_JoinSigningSessionServer = grpc.BidiStreamingServer[SessionMessage, SessionMessage]

func _MPCNode_SubmitSignatureShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServer).SubmitSignatureShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNode_SubmitSignatureShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServer).SubmitSignatureShare(ctx, req.(*ShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCNode_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNode_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MPCNode_ServiceDesc is the grpc.ServiceDesc for MPCNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MPCNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mpc.v1.MPCNode",
	HandlerType: (*MPCNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitSignatureShare",
			Handler:    _MPCNode_SubmitSignatureShare_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _MPCNode_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "JoinSigningSession",
			Handler:       _MPCNode_JoinSigningSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/mpc/v1/mpc.proto",
}

const (
	MPCCoordinator_CreateSigningSession_FullMethodName = "/mpc.v1.MPCCoordinator/CreateSigningSession"
	MPCCoordinator_GetSessionStatus_FullMethodName     = "/mpc.v1.MPCCoordinator/GetSessionStatus"
	MPCCoordinator_AggregateSignatures_FullMethodName  = "/mpc.v1.MPCCoordinator/AggregateSignatures"
)

// MPCCoordinatorClient is the client API for MPCCoordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MPCCoordinatorClient interface {
	// 创建签名会话
	CreateSigningSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	// 获取会话状态
	GetSessionStatus(ctx context.Context, in *SessionStatusRequest, opts ...grpc.CallOption) (*SessionStatusResponse, error)
	// 聚合签名
	AggregateSignatures(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*AggregateResponse, error)
}

type mPCCoordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewMPCCoordinatorClient(cc grpc.ClientConnInterface) MPCCoordinatorClient {
	return &mPCCoordinatorClient{cc}
}

func (c *mPCCoordinatorClient) CreateSigningSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, MPCCoordinator_CreateSigningSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCCoordinatorClient) GetSessionStatus(ctx context.Context, in *SessionStatusRequest, opts ...grpc.CallOption) (*SessionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionStatusResponse)
	err := c.cc.Invoke(ctx, MPCCoordinator_GetSessionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCCoordinatorClient) AggregateSignatures(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*AggregateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AggregateResponse)
	err := c.cc.Invoke(ctx, MPCCoordinator_AggregateSignatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MPCCoordinatorServer is the server API for MPCCoordinator service.
// All implementations must embed UnimplementedMPCCoordinatorServer
// for forward compatibility.
type MPCCoordinatorServer interface {
	// 创建签名会话
	CreateSigningSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	// 获取会话状态
	GetSessionStatus(context.Context, *SessionStatusRequest) (*SessionStatusResponse, error)
	// 聚合签名
	AggregateSignatures(context.Context, *AggregateRequest) (*AggregateResponse, error)
	mustEmbedUnimplementedMPCCoordinatorServer()
}

// UnimplementedMPCCoordinatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMPCCoordinatorServer struct{}

func (UnimplementedMPCCoordinatorServer) CreateSigningSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSigningSession not implemented")
}
func (UnimplementedMPCCoordinatorServer) GetSessionStatus(context.Context, *SessionStatusRequest) (*SessionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionStatus not implemented")
}
func (UnimplementedMPCCoordinatorServer) AggregateSignatures(context.Context, *AggregateRequest) (*AggregateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AggregateSignatures not implemented")
}
func (UnimplementedMPCCoordinatorServer) mustEmbedUnimplementedMPCCoordinatorServer() {}
func (UnimplementedMPCCoordinatorServer) testEmbeddedByValue()                        {}

// UnsafeMPCCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MPCCoordinatorServer will
// result in compilation errors.
type UnsafeMPCCoordinatorServer interface {
	mustEmbedUnimplementedMPCCoordinatorServer()
}

func RegisterMPCCoordinatorServer(s grpc.ServiceRegistrar, srv MPCCoordinatorServer) {
	// If the following call panics, it indicates UnimplementedMPCCoordinatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MPCCoordinator_ServiceDesc, srv)
}

func _MPCCoordinator_CreateSigningSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCCoordinatorServer).CreateSigningSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCCoordinator_CreateSigningSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCCoordinatorServer).CreateSigningSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCCoordinator_GetSessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCCoordinatorServer).GetSessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCCoordinator_GetSessionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCCoordinatorServer).GetSessionStatus(ctx, req.(*SessionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCCoordinator_AggregateSignatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCCoordinatorServer).AggregateSignatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCCoordinator_AggregateSignatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCCoordinatorServer).AggregateSignatures(ctx, req.(*AggregateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MPCCoordinator_ServiceDesc is the grpc.ServiceDesc for MPCCoordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MPCCoordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mpc.v1.MPCCoordinator",
	HandlerType: (*MPCCoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSigningSession",
			Handler:    _MPCCoordinator_CreateSigningSession_Handler,
		},
		{
			MethodName: "GetSessionStatus",
			Handler:    _MPCCoordinator_GetSessionStatus_Handler,
		},
		{
			MethodName: "AggregateSignatures",
			Handler:    _MPCCoordinator_AggregateSignatures_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mpc/v1/mpc.proto",
}
