// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: proto/mpc/v1/registry.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MPCRegistry_RegisterNode_FullMethodName   = "/mpc.v1.MPCRegistry/RegisterNode"
	MPCRegistry_UnregisterNode_FullMethodName = "/mpc.v1.MPCRegistry/UnregisterNode"
	MPCRegistry_DiscoverNodes_FullMethodName  = "/mpc.v1.MPCRegistry/DiscoverNodes"
	MPCRegistry_GetNodeInfo_FullMethodName    = "/mpc.v1.MPCRegistry/GetNodeInfo"
	MPCRegistry_HealthCheck_FullMethodName    = "/mpc.v1.MPCRegistry/HealthCheck"
	MPCRegistry_WatchNodes_FullMethodName     = "/mpc.v1.MPCRegistry/WatchNodes"
)

// MPCRegistryClient is the client API for MPCRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 服务注册和发现服务
type MPCRegistryClient interface {
	// 注册节点
	RegisterNode(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// 注销节点
	UnregisterNode(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error)
	// 发现节点
	DiscoverNodes(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error)
	// 获取节点信息
	GetNodeInfo(ctx context.Context, in *NodeInfoRequest, opts ...grpc.CallOption) (*NodeInfoResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// 监听节点变化
	WatchNodes(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error)
}

type mPCRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewMPCRegistryClient(cc grpc.ClientConnInterface) MPCRegistryClient {
	return &mPCRegistryClient{cc}
}

func (c *mPCRegistryClient) RegisterNode(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, MPCRegistry_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCRegistryClient) UnregisterNode(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterResponse)
	err := c.cc.Invoke(ctx, MPCRegistry_UnregisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCRegistryClient) DiscoverNodes(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoveryResponse)
	err := c.cc.Invoke(ctx, MPCRegistry_DiscoverNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCRegistryClient) GetNodeInfo(ctx context.Context, in *NodeInfoRequest, opts ...grpc.CallOption) (*NodeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeInfoResponse)
	err := c.cc.Invoke(ctx, MPCRegistry_GetNodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCRegistryClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, MPCRegistry_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCRegistryClient) WatchNodes(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MPCRegistry_ServiceDesc.Streams[0], MPCRegistry_WatchNodes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MPCRegistry_WatchNodesClient = grpc.ServerStreamingClient[WatchResponse]

// MPCRegistryServer is the server API for MPCRegistry service.
// All implementations must embed UnimplementedMPCRegistryServer
// for forward compatibility.
//
// 服务注册和发现服务
type MPCRegistryServer interface {
	// 注册节点
	RegisterNode(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// 注销节点
	UnregisterNode(context.Context, *UnregisterRequest) (*UnregisterResponse, error)
	// 发现节点
	DiscoverNodes(context.Context, *DiscoveryRequest) (*DiscoveryResponse, error)
	// 获取节点信息
	GetNodeInfo(context.Context, *NodeInfoRequest) (*NodeInfoResponse, error)
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// 监听节点变化
	WatchNodes(*WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error
	mustEmbedUnimplementedMPCRegistryServer()
}

// UnimplementedMPCRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMPCRegistryServer struct{}

func (UnimplementedMPCRegistryServer) RegisterNode(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedMPCRegistryServer) UnregisterNode(context.Context, *UnregisterRequest) (*UnregisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterNode not implemented")
}
func (UnimplementedMPCRegistryServer) DiscoverNodes(context.Context, *DiscoveryRequest) (*DiscoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverNodes not implemented")
}
func (UnimplementedMPCRegistryServer) GetNodeInfo(context.Context, *NodeInfoRequest) (*NodeInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (UnimplementedMPCRegistryServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMPCRegistryServer) WatchNodes(*WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchNodes not implemented")
}
func (UnimplementedMPCRegistryServer) mustEmbedUnimplementedMPCRegistryServer() {}
func (UnimplementedMPCRegistryServer) testEmbeddedByValue()                     {}

// UnsafeMPCRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MPCRegistryServer will
// result in compilation errors.
type UnsafeMPCRegistryServer interface {
	mustEmbedUnimplementedMPCRegistryServer()
}

func RegisterMPCRegistryServer(s grpc.ServiceRegistrar, srv MPCRegistryServer) {
	// If the following call panics, it indicates UnimplementedMPCRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MPCRegistry_ServiceDesc, srv)
}

func _MPCRegistry_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCRegistryServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCRegistry_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCRegistryServer).RegisterNode(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCRegistry_UnregisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCRegistryServer).UnregisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCRegistry_UnregisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCRegistryServer).UnregisterNode(ctx, req.(*UnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCRegistry_DiscoverNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCRegistryServer).DiscoverNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCRegistry_DiscoverNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCRegistryServer).DiscoverNodes(ctx, req.(*DiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCRegistry_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCRegistryServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCRegistry_GetNodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCRegistryServer).GetNodeInfo(ctx, req.(*NodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCRegistry_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCRegistryServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCRegistry_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCRegistryServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCRegistry_WatchNodes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MPCRegistryServer).WatchNodes(m, &grpc.GenericServerStream[WatchRequest, WatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MPCRegistry_WatchNodesServer = grpc.ServerStreamingServer[WatchResponse]

// MPCRegistry_ServiceDesc is the grpc.ServiceDesc for MPCRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MPCRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mpc.v1.MPCRegistry",
	HandlerType: (*MPCRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _MPCRegistry_RegisterNode_Handler,
		},
		{
			MethodName: "UnregisterNode",
			Handler:    _MPCRegistry_UnregisterNode_Handler,
		},
		{
			MethodName: "DiscoverNodes",
			Handler:    _MPCRegistry_DiscoverNodes_Handler,
		},
		{
			MethodName: "GetNodeInfo",
			Handler:    _MPCRegistry_GetNodeInfo_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _MPCRegistry_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchNodes",
			Handler:       _MPCRegistry_WatchNodes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mpc/v1/registry.proto",
}
