// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: proto/mpc/v1/registry.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 注册相关消息
type RegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Node            *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Capabilities    []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                              // 支持的协议: ["gg18", "gg20", "frost"]
	SupportedChains []string               `protobuf:"bytes,3,rep,name=supported_chains,json=supportedChains,proto3" json:"supported_chains,omitempty"` // 支持的链: ["bitcoin", "ethereum"]
	Tags            map[string]string      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetSupportedChains() []string {
	if x != nil {
		return x.SupportedChains
	}
	return nil
}

func (x *RegisterRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RegisterResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RegistrationId string                 `protobuf:"bytes,2,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RegisteredAt   string                 `protobuf:"bytes,4,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *UnregisterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type UnregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_registry_proto_rawDescGZIP(), []int{3}
}

func (x *UnregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 发现相关消息
type DiscoveryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeType        string                 `protobuf:"bytes,1,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`                      // "coordinator", "participant", or empty for all
	Capabilities    []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                              // 需要的功能
	SupportedChains []string               `protobuf:"bytes,3,rep,name=supported_chains,json=supportedChains,proto3" json:"supported_chains,omitempty"` // 支持的链
	Limit           int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                                           // 返回数量限制
	HealthyOnly     bool                   `protobuf:"varint,5,opt,name=healthy_only,json=healthyOnly,proto3" json:"healthy_only,omitempty"`            // 只返回健康节点
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiscoveryRequest) Reset() {
	*x = DiscoveryRequest{}
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRequest) ProtoMessage() {}

func (x *DiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRequest.ProtoReflect.Descriptor instead.
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoveryRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *DiscoveryRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *DiscoveryRequest) GetSupportedChains() []string {
	if x != nil {
		return x.SupportedChains
	}
	return nil
}

func (x *DiscoveryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DiscoveryRequest) GetHealthyOnly() bool {
	if x != nil {
		return x.HealthyOnly
	}
	return false
}

type DiscoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResponse) Reset() {
	*x = DiscoveryResponse{}
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse) ProtoMessage() {}

func (x *DiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_registry_proto_rawDescGZIP(), []int{5}
}

func (x *DiscoveryResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *DiscoveryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 节点信息相关消息
type NodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfoRequest) Reset() {
	*x = NodeInfoRequest{}
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfoRequest) ProtoMessage() {}

func (x *NodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfoRequest.ProtoReflect.Descriptor instead.
func (*NodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_registry_proto_rawDescGZIP(), []int{6}
}

func (x *NodeInfoRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type NodeInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfoResponse) Reset() {
	*x = NodeInfoResponse{}
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfoResponse) ProtoMessage() {}

func (x *NodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfoResponse.ProtoReflect.Descriptor instead.
func (*NodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_registry_proto_rawDescGZIP(), []int{7}
}

func (x *NodeInfoResponse) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *NodeInfoResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// 健康检查相关消息
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CheckType     string                 `protobuf:"bytes,2,opt,name=check_type,json=checkType,proto3" json:"check_type,omitempty"` // "tcp", "http", "grpc"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_registry_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HealthCheckRequest) GetCheckType() string {
	if x != nil {
		return x.CheckType
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "passing", "warning", "critical"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	CheckedAt     string                 `protobuf:"bytes,4,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	Details       map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_registry_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetCheckedAt() string {
	if x != nil {
		return x.CheckedAt
	}
	return ""
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// 监听相关消息
type WatchRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NodeType             string                 `protobuf:"bytes,1,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	Capabilities         []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	IncludeHealthUpdates bool                   `protobuf:"varint,3,opt,name=include_health_updates,json=includeHealthUpdates,proto3" json:"include_health_updates,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_registry_proto_rawDescGZIP(), []int{10}
}

func (x *WatchRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *WatchRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *WatchRequest) GetIncludeHealthUpdates() bool {
	if x != nil {
		return x.IncludeHealthUpdates
	}
	return false
}

type WatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "node_registered", "node_unregistered", "node_updated", "health_changed"
	Node          *NodeInfo              `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Health        *HealthCheckResponse   `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"`
	EventTime     string                 `protobuf:"bytes,4,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_registry_proto_rawDescGZIP(), []int{11}
}

func (x *WatchResponse) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *WatchResponse) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *WatchResponse) GetHealth() *HealthCheckResponse {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *WatchResponse) GetEventTime() string {
	if x != nil {
		return x.EventTime
	}
	return ""
}

// 扩展的节点信息
type ExtendedNodeInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeType        string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"` // "coordinator", "participant"
	Endpoint        string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                 // gRPC endpoint, e.g., "localhost:50051"
	Version         string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "online", "offline", "maintenance"
	RegisteredAt    string                 `protobuf:"bytes,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	LastHeartbeat   string                 `protobuf:"bytes,7,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	LastSeen        string                 `protobuf:"bytes,8,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Capabilities    []string               `protobuf:"bytes,9,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	SupportedChains []string               `protobuf:"bytes,10,rep,name=supported_chains,json=supportedChains,proto3" json:"supported_chains,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags            map[string]string      `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HealthStatus    *HealthStatus          `protobuf:"bytes,13,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExtendedNodeInfo) Reset() {
	*x = ExtendedNodeInfo{}
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendedNodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendedNodeInfo) ProtoMessage() {}

func (x *ExtendedNodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendedNodeInfo.ProtoReflect.Descriptor instead.
func (*ExtendedNodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_registry_proto_rawDescGZIP(), []int{12}
}

func (x *ExtendedNodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExtendedNodeInfo) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *ExtendedNodeInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ExtendedNodeInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ExtendedNodeInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExtendedNodeInfo) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

func (x *ExtendedNodeInfo) GetLastHeartbeat() string {
	if x != nil {
		return x.LastHeartbeat
	}
	return ""
}

func (x *ExtendedNodeInfo) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

func (x *ExtendedNodeInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ExtendedNodeInfo) GetSupportedChains() []string {
	if x != nil {
		return x.SupportedChains
	}
	return nil
}

func (x *ExtendedNodeInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExtendedNodeInfo) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ExtendedNodeInfo) GetHealthStatus() *HealthStatus {
	if x != nil {
		return x.HealthStatus
	}
	return nil
}

var File_proto_mpc_v1_registry_proto protoreflect.FileDescriptor

const file_proto_mpc_v1_registry_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/mpc/v1/registry.proto\x12\x06mpc.v1\x1a\x19proto/mpc/v1/common.proto\"\xf6\x01\n" +
	"\x0fRegisterRequest\x12$\n" +
	"\x04node\x18\x01 \x01(\v2\x10.mpc.v1.NodeInfoR\x04node\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12)\n" +
	"\x10supported_chains\x18\x03 \x03(\tR\x0fsupportedChains\x125\n" +
	"\x04tags\x18\x04 \x03(\v2!.mpc.v1.RegisterRequest.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fregistration_id\x18\x02 \x01(\tR\x0eregistrationId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\rregistered_at\x18\x04 \x01(\tR\fregisteredAt\",\n" +
	"\x11UnregisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"H\n" +
	"\x12UnregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb7\x01\n" +
	"\x10DiscoveryRequest\x12\x1b\n" +
	"\tnode_type\x18\x01 \x01(\tR\bnodeType\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12)\n" +
	"\x10supported_chains\x18\x03 \x03(\tR\x0fsupportedChains\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12!\n" +
	"\fhealthy_only\x18\x05 \x01(\bR\vhealthyOnly\"\\\n" +
	"\x11DiscoveryResponse\x12&\n" +
	"\x05nodes\x18\x01 \x03(\v2\x10.mpc.v1.NodeInfoR\x05nodes\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"*\n" +
	"\x0fNodeInfoRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"P\n" +
	"\x10NodeInfoResponse\x12$\n" +
	"\x04node\x18\x01 \x01(\v2\x10.mpc.v1.NodeInfoR\x04node\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"L\n" +
	"\x12HealthCheckRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"check_type\x18\x02 \x01(\tR\tcheckType\"\x80\x02\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x04 \x01(\tR\tcheckedAt\x12B\n" +
	"\adetails\x18\x05 \x03(\v2(.mpc.v1.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x01\n" +
	"\fWatchRequest\x12\x1b\n" +
	"\tnode_type\x18\x01 \x01(\tR\bnodeType\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x124\n" +
	"\x16include_health_updates\x18\x03 \x01(\bR\x14includeHealthUpdates\"\xa8\x01\n" +
	"\rWatchResponse\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12$\n" +
	"\x04node\x18\x02 \x01(\v2\x10.mpc.v1.NodeInfoR\x04node\x123\n" +
	"\x06health\x18\x03 \x01(\v2\x1b.mpc.v1.HealthCheckResponseR\x06health\x12\x1d\n" +
	"\n" +
	"event_time\x18\x04 \x01(\tR\teventTime\"\xfb\x04\n" +
	"\x10ExtendedNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rregistered_at\x18\x06 \x01(\tR\fregisteredAt\x12%\n" +
	"\x0elast_heartbeat\x18\a \x01(\tR\rlastHeartbeat\x12\x1b\n" +
	"\tlast_seen\x18\b \x01(\tR\blastSeen\x12\"\n" +
	"\fcapabilities\x18\t \x03(\tR\fcapabilities\x12)\n" +
	"\x10supported_chains\x18\n" +
	" \x03(\tR\x0fsupportedChains\x12B\n" +
	"\bmetadata\x18\v \x03(\v2&.mpc.v1.ExtendedNodeInfo.MetadataEntryR\bmetadata\x126\n" +
	"\x04tags\x18\f \x03(\v2\".mpc.v1.ExtendedNodeInfo.TagsEntryR\x04tags\x129\n" +
	"\rhealth_status\x18\r \x01(\v2\x14.mpc.v1.HealthStatusR\fhealthStatus\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa6\x03\n" +
	"\vMPCRegistry\x12A\n" +
	"\fRegisterNode\x12\x17.mpc.v1.RegisterRequest\x1a\x18.mpc.v1.RegisterResponse\x12G\n" +
	"\x0eUnregisterNode\x12\x19.mpc.v1.UnregisterRequest\x1a\x1a.mpc.v1.UnregisterResponse\x12D\n" +
	"\rDiscoverNodes\x12\x18.mpc.v1.DiscoveryRequest\x1a\x19.mpc.v1.DiscoveryResponse\x12@\n" +
	"\vGetNodeInfo\x12\x17.mpc.v1.NodeInfoRequest\x1a\x18.mpc.v1.NodeInfoResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.mpc.v1.HealthCheckRequest\x1a\x1b.mpc.v1.HealthCheckResponse\x12;\n" +
	"\n" +
	"WatchNodes\x12\x14.mpc.v1.WatchRequest\x1a\x15.mpc.v1.WatchResponse0\x01B0Z.github.com/kashguard/go-mpc-wallet/internal/pbb\x06proto3"

var (
	file_proto_mpc_v1_registry_proto_rawDescOnce sync.Once
	file_proto_mpc_v1_registry_proto_rawDescData []byte
)

func file_proto_mpc_v1_registry_proto_rawDescGZIP() []byte {
	file_proto_mpc_v1_registry_proto_rawDescOnce.Do(func() {
		file_proto_mpc_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mpc_v1_registry_proto_rawDesc), len(file_proto_mpc_v1_registry_proto_rawDesc)))
	})
	return file_proto_mpc_v1_registry_proto_rawDescData
}

var file_proto_mpc_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_mpc_v1_registry_proto_goTypes = []any{
	(*RegisterRequest)(nil),     // 0: mpc.v1.RegisterRequest
	(*RegisterResponse)(nil),    // 1: mpc.v1.RegisterResponse
	(*UnregisterRequest)(nil),   // 2: mpc.v1.UnregisterRequest
	(*UnregisterResponse)(nil),  // 3: mpc.v1.UnregisterResponse
	(*DiscoveryRequest)(nil),    // 4: mpc.v1.DiscoveryRequest
	(*DiscoveryResponse)(nil),   // 5: mpc.v1.DiscoveryResponse
	(*NodeInfoRequest)(nil),     // 6: mpc.v1.NodeInfoRequest
	(*NodeInfoResponse)(nil),    // 7: mpc.v1.NodeInfoResponse
	(*HealthCheckRequest)(nil),  // 8: mpc.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 9: mpc.v1.HealthCheckResponse
	(*WatchRequest)(nil),        // 10: mpc.v1.WatchRequest
	(*WatchResponse)(nil),       // 11: mpc.v1.WatchResponse
	(*ExtendedNodeInfo)(nil),    // 12: mpc.v1.ExtendedNodeInfo
	nil,                         // 13: mpc.v1.RegisterRequest.TagsEntry
	nil,                         // 14: mpc.v1.HealthCheckResponse.DetailsEntry
	nil,                         // 15: mpc.v1.ExtendedNodeInfo.MetadataEntry
	nil,                         // 16: mpc.v1.ExtendedNodeInfo.TagsEntry
	(*NodeInfo)(nil),            // 17: mpc.v1.NodeInfo
	(*HealthStatus)(nil),        // 18: mpc.v1.HealthStatus
}
var file_proto_mpc_v1_registry_proto_depIdxs = []int32{
	17, // 0: mpc.v1.RegisterRequest.node:type_name -> mpc.v1.NodeInfo
	13, // 1: mpc.v1.RegisterRequest.tags:type_name -> mpc.v1.RegisterRequest.TagsEntry
	17, // 2: mpc.v1.DiscoveryResponse.nodes:type_name -> mpc.v1.NodeInfo
	17, // 3: mpc.v1.NodeInfoResponse.node:type_name -> mpc.v1.NodeInfo
	14, // 4: mpc.v1.HealthCheckResponse.details:type_name -> mpc.v1.HealthCheckResponse.DetailsEntry
	17, // 5: mpc.v1.WatchResponse.node:type_name -> mpc.v1.NodeInfo
	9,  // 6: mpc.v1.WatchResponse.health:type_name -> mpc.v1.HealthCheckResponse
	15, // 7: mpc.v1.ExtendedNodeInfo.metadata:type_name -> mpc.v1.ExtendedNodeInfo.MetadataEntry
	16, // 8: mpc.v1.ExtendedNodeInfo.tags:type_name -> mpc.v1.ExtendedNodeInfo.TagsEntry
	18, // 9: mpc.v1.ExtendedNodeInfo.health_status:type_name -> mpc.v1.HealthStatus
	0,  // 10: mpc.v1.MPCRegistry.RegisterNode:input_type -> mpc.v1.RegisterRequest
	2,  // 11: mpc.v1.MPCRegistry.UnregisterNode:input_type -> mpc.v1.UnregisterRequest
	4,  // 12: mpc.v1.MPCRegistry.DiscoverNodes:input_type -> mpc.v1.DiscoveryRequest
	6,  // 13: mpc.v1.MPCRegistry.GetNodeInfo:input_type -> mpc.v1.NodeInfoRequest
	8,  // 14: mpc.v1.MPCRegistry.HealthCheck:input_type -> mpc.v1.HealthCheckRequest
	10, // 15: mpc.v1.MPCRegistry.WatchNodes:input_type -> mpc.v1.WatchRequest
	1,  // 16: mpc.v1.MPCRegistry.RegisterNode:output_type -> mpc.v1.RegisterResponse
	3,  // 17: mpc.v1.MPCRegistry.UnregisterNode:output_type -> mpc.v1.UnregisterResponse
	5,  // 18: mpc.v1.MPCRegistry.DiscoverNodes:output_type -> mpc.v1.DiscoveryResponse
	7,  // 19: mpc.v1.MPCRegistry.GetNodeInfo:output_type -> mpc.v1.NodeInfoResponse
	9,  // 20: mpc.v1.MPCRegistry.HealthCheck:output_type -> mpc.v1.HealthCheckResponse
	11, // 21: mpc.v1.MPCRegistry.WatchNodes:output_type -> mpc.v1.WatchResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_mpc_v1_registry_proto_init() }
func file_proto_mpc_v1_registry_proto_init() {
	if File_proto_mpc_v1_registry_proto != nil {
		return
	}
	file_proto_mpc_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mpc_v1_registry_proto_rawDesc), len(file_proto_mpc_v1_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mpc_v1_registry_proto_goTypes,
		DependencyIndexes: file_proto_mpc_v1_registry_proto_depIdxs,
		MessageInfos:      file_proto_mpc_v1_registry_proto_msgTypes,
	}.Build()
	File_proto_mpc_v1_registry_proto = out.File
	file_proto_mpc_v1_registry_proto_goTypes = nil
	file_proto_mpc_v1_registry_proto_depIdxs = nil
}
